= Migrating VMware to AWS


== intro 
	
there is always the chance of being asked to take your IT with you when leaving your current office. you are then faced with the situation of shifting  your application load to the cloud or a weekend job and a rented van to take your racks on a tour of the best city on earth (london)


say you dont want to hire a van and you don’t  like weekend driving in London and you want to be all tech savvy and join the AWS stampede.

what do you then.

ok ...

think ...

== my options

you though hard, created an AWS test account and you are now a guru in all thing Amazon Web Service (you are a DIY kind of girl and you just know stuff when needed. no expensive tedious class based training).

to migrate Vms to AWS you figured you have 3 options:

1) lifandshift - basically over the last ten years you forgot to document and now you have dark corners in your infra and sometimes at night you wake up thinking 'how come this stuff still working?'. i this scenario try not to be the smart one and take the easy way out and forklift your vms.  


2)  somehow and despite having only .85 of person to rack, stack, water, feed , keep alive your IT, you managed to keep up with the times and build modular  applications. Bingo, you just have given your self the option of migrating your application in chunks.

3) you are rich and have time and there able to rebuild your apps from scratch. Ofcourse  you have to keep up with your the  your next doors and build nice digital  micro service not to forget clean interfaces 


The reality is you have no time and you have no time to do 2 or 3, so let lift and shift sms into AWS.


== Lift and shift



this what you have to do:


1) Tools 

install Ec2 cli tools. it is all explained here

https://docs.aws.amazon.com/cli/latest/userguide/installing.html

you need to install the cli on the machine where vm images reside

2) prep your vm

do this;

a) remove Vmware tools
b) disconnect peripherals (usb ....)
c) set IP assign to DHCP
3) shut vm down

3) make image reachable 

a) enable ssh or rdp
b) enable secure login and disable auto login 
3) enable GRUB

4) export it

a) export vm using the cli into ec2 

5) start 

 fire-up the newly created instance and you are good to go






   






















